### PR TITLE
Use sudo in #! line

### PR DESCRIPTION
**Pull request by ghost**
HOW DID WE NOT THINK OF THIS ALREADY

### CODE REVIEW

**Comment by lrvick** [comment]
This is a clever approach. Have you tested it?

**Comment by ghost** [comment]
Not for the hashbang script, but it -does- start in sudo mode if you write a quick Python script like this.

**Comment by lrvick** [comment]
Also what would we put in /etc/sudoers? Currently it looks like this:

https://github.com/hashbang/shell-etc/blob/master/sudoers#L30

I am not sure how sudo actually gets invoked here to make the specific sudo rule required.

**Comment by ghost** [comment]
That line says that all users (`ALL`) are allowed to, without a password (`NOPASSWD`), run the hashbangctl script. Working on a way to work around that now.

**Comment by ghost** [comment]
This would not work. Closing.

**Pull request closed without merging**
