### PR TITLE
Added possibility to fetch users keyf from github

### PR DESCRIPTION
**Pull request by m42e**
This should implement the feature requested in #2

### CODE REVIEW

**Comment by drGrove** [comment]
This looks good to me :D :+1:

**Comment by RyanSquared** [comment]
Looks good. I can't confirm the pull request until we have verified it's working.

**Comment by KellerFuchs** [comment]
Looks good for me too.  
I cannot test it immediately, though.

PS: A better commit name, with an expended description inside, would be more helpful.

**Comment by RyanSquared** [comment]
Bump - @lrvick does this look good enough for merging?

**Comment by lrvick** [comment]
lgtm

**Comment by daurnimator** [comment]
Fails... 

```
Actions:

  n - Change Name
  s - Change Shell
  a - Add SSH Public Key
  i - Import github SSH Public Keys
  d - Delete SSH Public Key
  S - Save changes
  h - Help
  q - Quit

> i

Traceback (most recent call last):
  File "/usr/local/bin/hashbangctl", line 153, in <module>
AttributeError: 'dict' object has no attribute 'login'
```

**Pull request merged**
